---
- name: block IP address
  hosts: checkpoint
  connection: httpapi

  tasks:
    - include_role:
        name: acl_manager
        tasks_from: block_ip
      vars:
        source_ip: 192.168.56.151
        destination_ip: 192.168.56.156
        ansible_network_os: checkpoint

