---
- name: delete block list entry
  hosts: checkpoint
  connection: httpapi

  tasks:
    - include_role:
        name: acl_manager
        tasks_from: unblock_ip
      vars:
        source_ip: 192.168.56.156
        destination_ip: 192.168.56.151
        ansible_network_os: checkpoint

